# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\A_Firstproject\study\k-digital4\07.GUI\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(705, 737)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(48)
        Dialog.setFont(font)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(180, 590, 321, 81))
        self.pushButton.setObjectName("pushButton")
        self.login_Button = QtWidgets.QPushButton(Dialog)
        self.login_Button.setGeometry(QtCore.QRect(210, 480, 261, 81))
        self.login_Button.setObjectName("login_Button")
        self.id = QtWidgets.QLineEdit(Dialog)
        self.id.setGeometry(QtCore.QRect(330, 290, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.id.setFont(font)
        self.id.setObjectName("id")
        self.id_label = QtWidgets.QLabel(Dialog)
        self.id_label.setGeometry(QtCore.QRect(130, 280, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.id_label.setFont(font)
        self.id_label.setObjectName("id_label")
        self.pw_label = QtWidgets.QLabel(Dialog)
        self.pw_label.setGeometry(QtCore.QRect(130, 360, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.pw_label.setFont(font)
        self.pw_label.setObjectName("pw_label")
        self.pw = QtWidgets.QLineEdit(Dialog)
        self.pw.setGeometry(QtCore.QRect(330, 370, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pw.setFont(font)
        self.pw.setObjectName("pw")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(180, 70, 361, 141))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "회원가입"))
        self.login_Button.setText(_translate("Dialog", "로그인"))
        self.id_label.setText(_translate("Dialog", "아이디"))
        self.pw_label.setText(_translate("Dialog", "비밀번호"))
        self.label.setText(_translate("Dialog", "디아블로 1"))
import 파이썬_rc
